project:
  type: book
  preview:
    port: 5555
  resources:
    - exercise/**.qmd
    - static/schedule.csv

book:
  title: 基礎演習
  search: false
  repo-url: https://github.com/kazuyanagimoto/course-kobe-firstyear-2026
  author:
    - name: 柳本和春
      email: yanagimoto@econ.kobe-u.ac.jp
      orcid: 0009-0007-1967-8304
      affiliations:
        - name: 神戸大学
  date: 2026-04-01
  chapters:
    - index.qmd
    - 01-quarto.qmd
    - 02-citation.qmd
  appendices:
    - 11-quarto.qmd
    - references.qmd

bibliography: references.bib
bibliographystyle: chicago-author-date

format:
  html:
    lightbox: true
    number-sections: true
    number-depth: 2
    theme:
      - cosmo
      - brand
      - static/custom.scss
    include-after-body:
      - text: |
          <script src="static/mermaid-icon.js"></script>

knitr:
  opts_chunk: 
    fig.align: center
    fig.retina: 3
    fig.width: 6
    fig.height: 3
    out.width: 90%
    collapse: true


freeze: auto